export const GET_PREV_CALENDAR = 'GET_PREV_CALENDAR';
export const GET_NEXT_CALENDAR = 'GET_NEXT_CALENDAR';

export const CHOOSE_DATE = 'CHOOSE_DATE';
export const CHOOSE_START_TAB = 'CHOOSE_START_TAB';
export const CHOOSE_END_TAB = 'CHOOSE_END_TAB';
